### ISSUE TITLE
Presenterm stuck after update

### ISSUE THREAD

**Issue by DanWlker** [mfontanini/presenterm#455]
Hi, I just updated to 0.10.1, and when attempting to use presenterm it just stops at this and does not go full screen, Ctrl-C and q does not do anything as well

![Image](https://github.com/user-attachments/assets/a45f2640-6acf-42c7-9e58-6f512b734758)

I'm using tmux on kitty 0.38.1, I tested it with kitty without tmux and ghostty, all are providing the same results. I installed it from brew on macos Sequoia 15.2

Any way to debug this?

**Comment by mfontanini** [comment]
Does 0.10.0 work or do you see the same behavior?

**Comment by mfontanini** [comment]
I have a macOS VM via quickemu that runs sequoia 15.2, but it has no GPU acceleration so I can't test ghostty/kitty/wezterm. I did test with iterm2 and terminal.app and I can't reproduce. Is this an arm or x64 based machine? 

If you run using `presenterm --image-protocol ascii-blocks thing.md` does it also hang? 

If anyone else is experiencing this please chime in. I unfortunately don't have a mac laptop so I can't easily reproduce.

As for debugging this, if this was linux I'd use strace but macOS doesn't have that. I tried using dtruss but it has no option to redirect the output to a file and using `dtruss presenterm .... 2>/tmp/somewhere` interferes with the queries being done to the terminal emulator and causes it to hang (although maybe this _is_ the issue and somehow you're hitting it). I wanted to set a timeout on these queries but didn't get to it; in theory the emulator should always answer.

Maybe `dtrace` would help here but I've never used it either and I don't think I'd want to trace specific syscalls. `read` and `write` for sure but that may not be enough to catch the issue.

**Comment by DanWlker** [comment]
Using `presenterm --image-protocol ascii-blocks` doesn't make it hang anymore at all. 

Though, I tried several times after the original issue post, it seems to work some of the times (rarely works), haven't managed to find a pattern to why it works sometimes but not for others.

My device is an M1pro macbook. I can help to run any debugging or logs and paste here if there is a way to get them

**Comment by DanWlker** [comment]
It is still happening with 0.10.0, I tried 0.9.0 and it works without issues, seems to be happening after 0.10.0

**Comment by mfontanini** [comment]
I just pushed a branch to try to guess a fix, can you try it?

```bash
git clone https://github.com/mfontanini/presenterm
cd presenterm
git checkout fix/mac-hang
cargo run examples/demo.md
```

**Comment by DanWlker** [comment]
![Image](https://github.com/user-attachments/assets/1186e5f1-1ef1-4cc3-ac1d-5642280d8104)
Seems to be stuck on this

**Comment by mfontanini** [comment]
In the meantime you can run this with `--image-protocol kitty-local` and that should work. What's broken is the kitty protocol detection, which is now run every time whereas before it was only run if we detected you were inside kitty/ghostty (which didn't work if you were on tmux). I'll look around later today and see if I can find a workaround. The issue here is I could make it timeout but that means you won't get proper image support which is a bad workaround.

**Comment by DanWlker** [comment]
yup running this with `--image-protocol kitty-local` worked. I tried running it without tmux it still hangs though

![Image](https://github.com/user-attachments/assets/8d800b12-5b70-48ef-be81-0738e45e50d4)

**Comment by mfontanini** [comment]
Are you certain running this outside of tmux, just straight kitty/ghostty, also doesn't work if you don't specify the image protocol? Just to be sure so I can try to reproduce

**Comment by DanWlker** [comment]
Nope working normally outside of tmux, my bad.

**Comment by mfontanini** [comment]
No worries, this is very helpful! So to sum up:

* Kitty/ghostty outside of tmux all good.
* Kitty/ghostty inside remix -> no good

**Comment by mfontanini** [comment]
And which tmux version are you using?

**Comment by DanWlker** [comment]
My tmux is 3.5a

**Comment by mfontanini** [comment]
Sorry for the interrogation but if you use --image-protocol _and_ tmux it does work?

**Comment by DanWlker** [comment]
No worries, yup it does work but the image does not show up

![Image](https://github.com/user-attachments/assets/2a5b8a71-e332-4513-b711-da40aa6182b5)

**Comment by mfontanini** [comment]
Nice, this is really good info. 2 things:

1. Can you try setting `allow-passthrough` on tmux to `on` and try again?
2. Before 0.10.0, where it worked: did images also work for you while inside tmux? Or does the demo presentation work but images don't show up like above?

**Comment by DanWlker** [comment]
1. Alright let me try this
2. I tried running it with `./presenterm example/demo.md` but I got this:

![Image](https://github.com/user-attachments/assets/b02522cf-1844-4dfb-b187-0216d301c486)

Trying it with my own file I get this:

![Image](https://github.com/user-attachments/assets/7ca3317a-6f57-490c-b140-19cc23912e62)

**Comment by mfontanini** [comment]
Yeah sorry there's new stuff in there. Just create an .md with `![](examples/doge.png)` instead and run it with that?

**Comment by mfontanini** [comment]
Okay sorry, you did that.

**Comment by DanWlker** [comment]
![Image](https://github.com/user-attachments/assets/128927ad-35b5-4864-bbca-9af83b6ee63a)

Doge renders like this

**Comment by mfontanini** [comment]
I think passthrough is the thing that'll fix it.

**Comment by DanWlker** [comment]
you are right, allow passthrough allows the image to be rendered correctly

![Image](https://github.com/user-attachments/assets/f0fa72f2-584e-493c-8067-4ea9c5473eec)

**Comment by mfontanini** [comment]
So, what's happening is:

* Images in tmux (sixel or kitty, I think tmux in iterm2 is not supported here) requires `allow-passthrough` to be enabled. This is what allows presenterm to tell tmux to forward the escape codes to print the image all the way to the terminal emulator.
* Before 0.10.0, if you were inside tmux, image protocol detection wasn't run.
* In >= 0.10.0, when you start presenterm if we can't determine your terminal (most likely case is you're inside tmux), we try to detect if the kitty protocol / sixel is supported. The problem here is the detection relies on tmux forwarding the queries to the emulator. Because it will only do that if passthrough is enabled, then we never get any answers and get stuck. 

Ideally there would be a timeout on the query but I think this is a bit tricky because there's not a cross platform way of using non blocking io here (e.g. we can't "try to read for up to a second" easily). But I have another idea that should work, I'll give it a shot now.

> Thanks for your patience and quick response

Not at all! Thank _you_ for your patience and being so responsive!

> I'd recommend adding a line to the readme for tmux users

Absolutely, will do that. I've been using passthrough all the time and completely forgot this was necessary for passthrough to happen.

**Comment by mfontanini** [comment]
This should be fixed after #456 but let me know otherwise! Thanks again for the report!
